spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/elearning_db
    username: root
    password: qwerty
springdoc:
  swagger-ui:
    path: /swagger-ui-doc.html